### ISSUE TITLE
Needed to install ImageMagick prior to bundle install

### ISSUE THREAD

**Issue by cassiehelms** [girldevelopit/gdi-website#130]
_NOTE: This is an update from the original issue and is meant to help make the goals of the fix cleaner._

**Description**
_On Mac OSX 10.7.5, bundle install seemed to get hung up on `gem install rmagick`_

**Ask**
_Add to the docs that `imagemagick` should be installed prior to running `bundle install`_

**To Do**
- [ ] Add `brew install imagemagick` to the install documentation.

**Comment by kstack7** [comment]
We have another GDI chapter leader that hit this wall too...I'll talk to her and see if that was a similar path she took. Either way it doesn't hurt to add as an extra tip while installing.

**Comment by bayendor** [comment]
Please see #159.  `Carrierwave` appears to only need `rmagick` gem for` jruby`. The recommended gem is `mini_magick` installed as a `carrierwave` dependency.  In turn `mini_magick` requires `imagemagick` be installed on the user machine.

**Comment by juliaelman** [comment]
@bayendor thanks for pointing this out! How do you think we should move forward from here in regards to this issue? Is it still needed?

**Comment by bayendor** [comment]
@juliaelman the `rmagick` gem was removed with #172, as part of the cleanup.  `mini_magick` is now a required gem dependency of CarrierWave.

From the CarrierWave docs
> ...you must have Imagemagick and MiniMagick installed to do image resizing. Since MiniMagick is a Ruby interface for Imagemagick which is a C program. This is why MiniMagick fails on 'bundle install' without Imagemagick installed.

The site does image resizing in three separate file uploader classes, and since `mini_magick` is a required dependency, we will have to update the install docs to have aspiring devs `brew install imagemagick` as one of the early steps.  Currently we don't appear to list this as an environment setup step.

**Comment by juliaelman** [comment]
@bayendor awesome! I am updating the issue with the #83 format that clearly states these changes. Thank you! :cake:

**Comment by kstack7** [comment]
Update: Windows platform is now GDI-friendly :) and ImageMagick is still a mandatory install. Will be updating to both the existing setup process and the pending Windows setup process. Thanks for the insight!
