### ISSUE TITLE
header link css too tall 

### ISSUE THREAD

**Issue by johnmarinelli** [girldevelopit/gdi-website#336]
**Description**
Hovering over a link in the navbar reveals a slightly too-tall black box.

**Ask**
Make the black box fit to the height of the navbar

**To Do**
- Change the css to reflect the appropriate height for navbar links

_Include any images, steps to recreate, notes, emojis, or whatever._
![gdi](https://cloud.githubusercontent.com/assets/3382949/8540446/c7cc39d8-243a-11e5-8f40-e6516548e765.png)

**Comment by kstack7** [comment]
Hello @johnmarinelli! We greatly appreciate your contributions and we that you used our issue template as well! :+1: 

We actually had a discussion over this on a different issue (https://github.com/girldevelopit/gdi-new-site/issues/221) and left the links as you see them now due to the intended design.

Please feel free to tackle any other bugs, fixes, or throw in some suggestions! I will close this in the meantime.

**Comment by johnmarinelli** [comment]
whoops, my bad!  thanks.
