### ISSUE TITLE
Add Outreach & Special Initiatives Lead to Jobs page

### ISSUE THREAD

**Issue by corinnepw** [girldevelopit/gdi-website#549]
**Description**
GDI is hiring a full-time Outreach and Special Initiatives Lead! To advertise the role and enable easy sharing among CLs and our network, we'd like to add it to our jobs pages.

**Ask**
Add Outreach and Special Initiatives job description to girldevelopit.com/jobs

**Additional Info**
Please find all content to be added here: https://docs.google.com/a/girldevelopit.com/document/d/135mhfFDUJfvqCY-XpxG5PuVO4ECsz250rG_WaT9aIoA/edit

**Comment by cecilianempire** [comment]
Hi Corinne, you won't need to post that position onto your jobs page because I'm your person for this role! Attached is my resume and a letter of recommendation from a VP at Princess Cruise Lines (so you can confirm I'm not a creep). I have time to chat today at your convenience. Thanks! 

[2017 CM (GDI).pdf](https://github.com/girldevelopit/gdi-website/files/1110190/2017.CM.GDI.pdf)

[From Robert Morgenstern.pdf](https://github.com/girldevelopit/gdi-website/files/1110107/From.Robert.Morgenstern.pdf)

**Comment by corinnepw** [comment]
@cecilianempire 😂  Love this! Please apply via https://gethired.com/a/9a0a1a12-6fd2-4bbd-9b0b-9a4396cb0552 if you haven't already! 

This issue is up for grabs still for anyone to take! Thank you :)
